api_key = ""
model = "gpt-3.5-turbo"
# Default context used by OpenAI; you can amend it or comment it out
context = "You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible."
vi_mode = false
visible_overflow = true
