api_key = ""
model = "gpt-3.5-turbo"
vi_mode = false
visible_overflow = true

[contexts]
# Default context used by OpenAI
default = "You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible."
